'use strict';
/* AI 일일 코멘트 — daily-commentary.yml 자동 생성(wrap_commentary.mjs). app.js 가 우선 사용, 없으면 commentary.js/desc 로 fallback. */
const COMMENT_DAILY = {
  "김프": {"ko":"국내 프리미엄 소폭 플러스📈","en":"Kimchi premium ticks positive","why":{"ko":"업비트 가격이 해외보다 비싸질수록 한국 개인투자자 매수 열기가 강하다는 뜻. 김프가 크게 뛰면 국내발 과열 신호로 읽어요.","en":"The more Korean (Upbit) prices run above global ones, the hotter local retail buying is. A big spike reads as Korea-driven overheating."},"now":{"ko":"+0.41%로 완만한 플러스라 국내 심리는 살짝 우호적. 다만 어제보다 오른 반등이라 뚜렷한 추세로 보긴 일러요.","en":"At +0.41% it's mildly positive for sentiment, but it's a rebound from a lower level yesterday — too early to call it a trend."}},
  "공포·탐욕": {"ko":"공포·탐욕 딱 중립😐","en":"Fear & Greed sits neutral","why":{"ko":"변동성·거래량·소셜 등을 종합해 시장 심리의 과열·공포 정도를 보여줘요. 극단값일수록 반전 가능성이 커진다고 봐요.","en":"This index blends volatility, volume, and social buzz to gauge market mood. Extreme readings often hint at a potential reversal."},"now":{"ko":"지금 51로 중립 근처라 뚜렷한 쏠림 없이 시장이 관망 중인 분위기예요.","en":"At 51, it's right near neutral — no strong bias, the market looks like it's waiting."}},
  "소셜 멘션": {"ko":"소셜 언급량 조용한 편🔇","en":"Social mentions running quiet","why":{"ko":"SNS 언급이 급증하면 신규 관심·FOMO 유입 신호, 급감하면 대중 관심이 식었다는 뜻으로 봐요.","en":"A surge in social mentions signals fresh interest and FOMO inflows; a drop suggests fading public attention."},"now":{"ko":"평균 대비 -20%로 언급량이 줄어든 상태라 리테일 관심이 다소 식어있는 편이에요.","en":"Mentions are down 20% vs average, suggesting retail interest has cooled somewhat."}},
  "구글 검색": {"ko":"구글 검색도 시들🔍","en":"Google searches cooling off","why":{"ko":"'비트코인' 같은 키워드 검색량은 신규 개인투자자 유입의 선행지표로 여겨져요. 검색이 늘면 대중 관심이 커지는 신호예요.","en":"Searches for terms like 'bitcoin' are seen as a leading signal of new retail entrants — rising searches mean growing public interest."},"now":{"ko":"평균 대비 -25%로 검색 관심이 줄어든 상태라 신규 유입 동력은 약한 편이에요.","en":"Down 25% vs average, so the pull for fresh entrants looks weak right now."}},
  "앱 순위": {"ko":"코인베이스 앱, 순위 밀림📉","en":"Coinbase app ranking slips","why":{"ko":"앱스토어 순위가 오르면 신규 가입자가 몰린다는 뜻이라 리테일 온보딩 속도를 가늠하는 지표예요.","en":"A rising app store rank means new signups are surging, tracking the pace of retail onboarding."},"now":{"ko":"현재 35위로 상위권과 거리가 있어 신규 개인 유입이 활발하다고 보기는 어려워요.","en":"Sitting at #35, it's far from the top, so a fresh wave of retail users isn't really showing up."}},
  "ETF 플로우": {"ko":"ETF 7일은 유출, 어제는 유입↔️","en":"ETF: 7d outflow, inflow yesterday","why":{"ko":"미국 현물 ETF는 기관 자금이 코인시장에 들어오는 핵심 통로예요. 순유입이 늘면 기관 매수세로 해석돼요.","en":"US spot ETFs are a key channel for institutional money into crypto — rising net inflows signal institutional buying."},"now":{"ko":"최근 7일은 순유출(-$336M)이지만 어제 하루는 +$147M 순유입으로 반전, 기관 심리가 완전히 식은 건 아니에요.","en":"The past 7 days show net outflows (-$336M), but yesterday flipped to +$147M inflow — institutional appetite isn't fully gone."}},
  "코인베이스 프리미엄": {"ko":"코인베이스 프리미엄 마이너스","en":"Coinbase premium turns negative","why":{"ko":"코인베이스 가격이 해외보다 비싸면 미국 기관·개인 매수세가 강하다는 신호로 봐요.","en":"When Coinbase trades above global prices, it signals stronger US institutional and retail buying."},"now":{"ko":"지금은 -0.066%로 미국 쪽이 오히려 싸게 거래되고, 하루새 더 낮아져 미국발 매수세가 약해진 모습이에요.","en":"At -0.066%, US prices are actually cheaper, and it slipped further over the day — US buying pressure looks weak."}},
  "CME 선물": {"ko":"CME OI 한달새 뚝📉","en":"CME futures OI drops MoM","why":{"ko":"CME는 기관들이 주로 쓰는 규제된 선물시장이라 미결제약정(OI) 증감은 기관 관심도를 보여줘요.","en":"CME is the regulated futures venue institutions favor, so its open interest tracks institutional engagement."},"now":{"ko":"한 달 새 -8%로 줄어들어 기관 쪽 레버리지·관심이 다소 후퇴한 상태예요.","en":"Down 8% over the month, showing institutional leverage and interest have pulled back a bit."}},
  "스테이블 공급": {"ko":"스테이블 공급 완만한 증가","en":"Stablecoin supply inching up","why":{"ko":"스테이블코인 시총은 코인을 살 준비가 된 대기자금이에요. 늘어나면 잠재 매수여력이 커진다고 봐요.","en":"Stablecoin market cap represents sidelined buying power — growth means more potential dry powder for crypto purchases."},"now":{"ko":"4주간 +1.3%로 완만히 늘었지만 최근 1주는 소폭 감소해 매수 대기자금 증가세가 둔화된 편이에요.","en":"Up 1.3% over 4 weeks, but the latest week dipped slightly — the growth in dry powder has slowed."}},
  "$STRC": {"ko":"STRC 액면 근접, 이틀째 하락","en":"STRC near par, sliding 2 days","why":{"ko":"스트래티지의 우선주 STRC는 $100 액면 유지를 목표로 설계돼, 액면 위·아래 여부가 BTC 관련 수요 강도를 보여줘요.","en":"Strategy's STRC preferred stock targets a $100 par value — trading above or below it signals demand for BTC-linked assets."},"now":{"ko":"$97.14로 액면 근처지만 이틀 연속(-$1.77, -$1.50) 하락 중이라 수요가 조금씩 식고 있는 신호예요.","en":"At $97.14, near par but down two days straight (-$1.77, -$1.50) — a sign demand is gradually cooling."}},
  "$MSTR": {"ko":"MSTR 52주 저점권, 이틀 하락","en":"MSTR near 52wk low, 2 days down","why":{"ko":"MSTR은 비트코인을 대량 보유한 트레저리 기업 주식이라 52주 범위 내 위치가 기관 레버리지 수요를 대변해요.","en":"MSTR is a BTC treasury stock, so its position in the 52-week range reflects institutional leverage demand."},"now":{"ko":"52주 범위 하단권(~17%)인데 이틀 연속(-$7, -$1) 하락해 기관 수요가 약해지는 흐름이에요.","en":"Sitting near the bottom of its 52-week range (~17%) and down two days straight — institutional demand looks weak."}},
  "펀딩비": {"ko":"펀딩비, 원리만 참고😶","en":"Funding rate: read with caution","why":{"ko":"무기한 선물 펀딩비는 롱숏 쏠림을 보여주는 지표로, 크게 플러스면 롱 과열로 되돌림 위험이 커진다고 봐요.","en":"Perpetual futures funding rate shows long/short skew — a big positive reading means long crowding and higher pullback risk."},"now":{"ko":"이 값은 실시간 조회가 막혀 최신 수치가 아닐 수 있어요. 지금 방향성 판단보다는 구조 이해용으로만 참고하세요.","en":"Live data here may be stale, so this reading may not reflect the current market — treat it as background context, not a real-time signal."}},
  "OI": {"ko":"OI도 최신값 아닐 수도","en":"OI reading may be outdated","why":{"ko":"선물 미결제약정이 늘면 레버리지 베팅이 커진다는 뜻이라 시장 과열·변동성 확대 가능성을 보여줘요.","en":"Rising open interest means growing leveraged bets, hinting at potential overheating or bigger swings."},"now":{"ko":"실시간 조회가 막혀 있어 지금 수치를 그대로 믿긴 어려워요. 늘어나는 OI는 원래 과열 신호로 해석된다는 정도만 참고하세요.","en":"Live access is blocked, so don't take this number at face value — just note that rising OI is normally read as overheating."}},
  "롱/숏": {"ko":"롱숏비율도 구식 데이터","en":"Long/short ratio data is stale","why":{"ko":"상위 트레이더들의 롱/숏 포지션 쏠림은 시장 참여자들의 방향성 베팅을 보여주는 지표예요.","en":"The long/short skew among top traders shows how directionally they're positioned."},"now":{"ko":"실시간 값이 아니라 지금 쏠림 정도를 단정하긴 어려워요. 롱이 많을수록 과열 신호란 원리만 기억하세요.","en":"Since it's not live, don't read too much into the current skew — just remember heavier long positioning usually signals overheating."}},
  "풋/콜": {"ko":"풋/콜, 콜 쪽에 무게","en":"Put/call tilts toward calls","why":{"ko":"옵션시장에서 풋(하락 베팅)과 콜(상승 베팅)의 미결제약정 비율로 시장의 방향성 기대를 가늠해요.","en":"This options ratio of puts (bearish bets) to calls (bullish bets) gauges the market's directional expectations."},"now":{"ko":"0.55로 중립(~0.7)보다 낮아 콜 쪽 수요가 우세, 옵션시장은 상승 쪽에 좀 더 기울어 있어요.","en":"At 0.55, below the ~0.7 neutral zone, call demand leads — options traders lean slightly bullish."}},
  "DVOL": {"ko":"변동성지수 소폭 부담","en":"Vol index a touch elevated","why":{"ko":"옵션 내재변동성이 높으면 시장이 큰 변동을 예상한다는 뜻으로, 과도하게 높으면 패닉·불안 신호로 봐요.","en":"Higher implied volatility means the market expects bigger swings — extreme readings can signal panic or anxiety."},"now":{"ko":"38.8로 다소 높은 편이라 시장이 변동성 확대를 경계하는 분위기예요.","en":"At 38.8, it's on the higher side, suggesting the market is bracing for more turbulence."}},
  "SOPR": {"ko":"SOPR 1 밑, 손실실현 우위","en":"SOPR below 1, losses realized","why":{"ko":"SOPR은 코인을 매도한 투자자들이 이익을 봤는지 손실을 봤는지를 보여주는 온체인 지표예요.","en":"SOPR shows whether coins moving on-chain are being sold at a profit or a loss."},"now":{"ko":"0.99로 1 아래라 손실 실현 매물이 약간 더 많은 상태, 투심이 살짝 위축된 신호예요.","en":"At 0.99, below 1, slightly more coins are selling at a loss — a mild sign of cautious sentiment."}},
  "거래소 보유량": {"ko":"거래소 잔고 90일째 감소","en":"Exchange reserves down 90d","why":{"ko":"거래소에서 코인이 빠져나가면 장기보유·자체보관 성향이 커진다는 뜻이라 매도 압력이 줄어든다고 봐요.","en":"Coins leaving exchanges suggest more long-term holding and self-custody, implying less selling pressure."},"now":{"ko":"90일간 -6%로 꾸준히 줄어 공급이 축소되는 흐름, 구조적으로는 우호적인 신호예요.","en":"Down 6% over 90 days — supply keeps shrinking, a structurally supportive backdrop."}},
  "채굴자 매도": {"ko":"채굴자 매도압력 커진 편","en":"Miner sell pressure elevated","why":{"ko":"채굴자 수익성이 높아지면 보유물량을 더 팔 유인이 커져 매도압력을 키운다고 봐요(Puell Multiple).","en":"When miner profitability rises, miners have more incentive to sell holdings, adding to sell pressure (Puell Multiple)."},"now":{"ko":"0.93 수준으로 채굴자發 매도 압력이 다소 높은 구간이라 공급 측면에서 약한 역풍이에요.","en":"At 0.93, miner-driven sell pressure looks somewhat elevated — a mild headwind from the supply side."}},
  "고래 축적": {"ko":"고래들 열심히 사모으는중🐋","en":"Whales are stacking hard","why":{"ko":"대형 지갑의 순매집·분배 추세는 스마트머니로 불리는 큰손들의 방향성을 보여주는 온체인 지표예요.","en":"Large wallet accumulation vs distribution tracks the direction 'smart money' whales are leaning."},"now":{"ko":"0.92로 축적 우위가 뚜렷해 고래들이 순매집 중인 흐름, 구조적으로 우호적인 신호예요.","en":"At 0.92, accumulation clearly dominates — whales are net buying, a structurally bullish backdrop."}},
  "USDT.D": {"ko":"테더 도미넌스 거의 그대로","en":"USDT dominance barely moved","why":{"ko":"스테이블코인 비중이 줄면 그 자금이 위험자산(코인)으로 이동한다는 뜻이라 역지표로 읽어요.","en":"A falling stablecoin share implies money rotating into risk assets like crypto — so it's read inversely."},"now":{"ko":"7.05%로 큰 변화가 없어 위험선호 심리도 뚜렷한 방향 없이 잠잠한 편이에요.","en":"At 7.05% with little change, risk appetite looks quiet without a clear direction."}},
  "ATH 낙폭": {"ko":"전고점 대비 -40% 근처","en":"~40% off all-time high","why":{"ko":"사상 최고가로부터의 거리는 지금이 사이클의 어느 국면(초입·과열·조정)인지 가늠하는 지표예요.","en":"Distance from the all-time high helps gauge which phase of the cycle (early, overheated, correction) the market is in."},"now":{"ko":"-39.9%로 고점에서 꽤 내려온 상태라 과열보다는 조정 국면에 가까운 위치예요.","en":"Down 39.9% from the peak, it's positioned more like a correction phase than overheating."}},
  "증시 쏠림": {"ko":"대형주 쏠림 보통 수준","en":"Mega-cap tilt is moderate","why":{"ko":"대형주(주로 AI·반도체)에 돈이 몰릴수록 위험자본이 그쪽에 묶여 코인으로 갈 여력이 줄어든다고 봐요(역방향).","en":"The more money concentrates in mega-caps (mostly AI/chips), the less risk capital is free to flow into crypto (inverse read)."},"now":{"ko":"59/100으로 쏠림이 극단은 아니라 코인 쪽으로도 어느 정도 자금 여력이 남아있는 상태예요.","en":"At 59/100, the concentration isn't extreme, leaving some room for capital to flow toward crypto too."}},
  "FED 유동성": {"ko":"연준 유동성 3개월째 축소","en":"Fed liquidity shrinking, 3mo","why":{"ko":"연준이 돈을 풀면(대차대조표-TGA-RRP↑) 그 자금이 위험자산으로 흘러 코인에 우호적, 반대면 역풍이에요.","en":"When the Fed's net liquidity (balance sheet minus TGA minus RRP) rises, funds flow into risk assets like crypto — and vice versa."},"now":{"ko":"3개월간 -1.3%로 줄어드는 추세라 유동성 측면에서는 약한 역풍이 이어지고 있어요.","en":"Down 1.3% over 3 months, so liquidity remains a mild headwind for now."}},
  "M2 유동성": {"ko":"M2 완만한 증가세","en":"M2 growing at a steady pace","why":{"ko":"통화량(M2)이 늘면 시중에 돈이 많아져 시차를 두고 위험자산·코인 가격에 우호적으로 작용한다고 봐요.","en":"Growing money supply (M2) means more cash in the system, which tends to lift risk assets like crypto with a lag."},"now":{"ko":"전년 대비 +5.41%로 꾸준히 늘고 있어 중장기적으로는 우호적인 배경이에요.","en":"Up 5.41% year-over-year, a steady tailwind for the medium-to-long-term backdrop."}},
  "미국 증시 추세": {"ko":"미 증시 1주째 하락세","en":"US stocks trending down, 1wk","why":{"ko":"코인은 위험자산이라 증시 상승(위험선호)에 동조, 하락(위험회피)엔 함께 눌리는 경향이 있어요.","en":"As a risk asset, crypto tends to move with stocks — rising in risk-on moods, falling in risk-off ones."},"now":{"ko":"최근 1주 -1.1%로 하락추세라 단기적으로는 코인에도 약한 역풍이 부는 편이에요.","en":"Down 1.1% over the past week, a mild short-term headwind for crypto too."}},
  "CLARITY": {"ko":"클래리티법 통과확률 급락","en":"CLARITY Act odds plunging","why":{"ko":"미 시장구조법(CLARITY Act) 통과는 규제 불확실성을 낮춰 기관 자금 유입을 촉진할 수 있는 재료예요.","en":"Passage of the CLARITY Act would reduce regulatory uncertainty, potentially opening the door to more institutional inflows."},"now":{"ko":"통과확률이 5%까지 내려왔고 이틀 연속(-11%p, -19%p) 급락 중이라 규제 기대감은 크게 꺾인 상태예요.","en":"Odds have fallen to 5% and dropped sharply two days straight (-11pp, -19pp) — regulatory optimism has clearly faded."}},
  "DXY": {"ko":"달러 3개월째 약세","en":"Dollar weakening over 3 months","why":{"ko":"달러가 강해지면 대체자산인 코인엔 역풍, 달러가 약해지면 코인을 포함한 위험자산에 우호적으로 작용해요.","en":"A stronger dollar is usually a headwind for alternative assets like crypto; a weaker dollar tends to help risk assets."},"now":{"ko":"3개월간 -1.6%로 달러가 약세 흐름이라 코인 입장에선 약한 순풍이 부는 편이에요.","en":"Down 1.6% over 3 months, the dollar's softness offers crypto a mild tailwind."}},
  "반도체 독주장": {"ko":"반도체 쏠림 풀리는 중","en":"Chip-stock crowding easing","why":{"ko":"반도체가 증시를 계속 앞서면 자금이 그쪽에 쏠려 코인까지 갈 여력이 줄어든다고 봐요(역방향 지표).","en":"When chip stocks keep outperforming, capital concentrates there, leaving less for crypto (an inverse indicator)."},"now":{"ko":"최근 1개월 반도체가 시장 대비 -5.5%로 상대적으로 밀려 쏠림이 완화, 코인엔 우호적인 신호예요.","en":"Over the past month, chips lagged the market by -5.5% relatively, easing the crowding — a favorable sign for crypto."}}
};
const COMMENT_DAILY_AT = "2026-09-16 09:57 KST";
