'use strict';
/* AI 일일 코멘트 — daily-commentary.yml 자동 생성(wrap_commentary.mjs). app.js 가 우선 사용, 없으면 commentary.js/desc 로 fallback. */
const COMMENT_DAILY = {
  "김프": {"ko":"국내 온기 살짝 도는 중 🌡️","en":"Korea warming up a bit","why":{"ko":"업비트 가격이 해외보다 비싸면 국내 매수세가 강하다는 뜻이에요. 김프가 크게 붙을수록 리테일 과열 신호로 읽혀 불장 분위기와 연결됩니다.","en":"When Upbit trades above global prices, Korean buying demand is strong. A large premium signals retail heat, which tends to accompany bull phases."},"now":{"ko":"김프 +0.94%로 과열은 아니고 온건한 우호 구간이에요. 이틀 누적으로 +0.77%p 올라 국내 수요가 조금씩 살아나는 흐름입니다.","en":"A +0.94% premium is mild support, not overheating. It rose 0.77pp over two days, so Korean demand is slowly picking up."}},
  "공포·탐욕": {"ko":"탐욕 쪽으로 기우는 심리","en":"Sentiment leans greedy","why":{"ko":"투자자 심리를 0~100으로 요약한 지수예요. 극공포는 바닥, 극탐욕은 과열 신호로 자주 쓰여 시장 온도를 가늠하는 데 도움이 됩니다.","en":"This index sums up investor mood on a 0-100 scale. Extreme fear often marks bottoms and extreme greed marks overheating, helping gauge market temperature."},"now":{"ko":"지수 67로 탐욕 구간이지만 극단(75+)은 아니라 아직 우호적이에요. 과열 경고까지는 여유가 조금 남아 있는 상태입니다.","en":"At 67 it is in greed territory but below the extreme 75+ zone, so still supportive. There is some room before overheating warnings."}},
  "소셜 멘션": {"ko":"SNS는 아직 조용해요 😶","en":"Social buzz is quiet","why":{"ko":"X와 레딧에서 코인 언급이 늘면 개인 관심과 FOMO가 커지고 있다는 뜻이에요. 언급량 급증은 보통 상승 국면 후반에 두드러집니다.","en":"Rising coin mentions on X and Reddit show growing retail interest and FOMO. Spikes in chatter often stand out in the later stages of rallies."},"now":{"ko":"언급량이 평균보다 20% 낮아 리테일 관심이 식어 있어요. 아직 군중이 몰리지 않아 불장 열기는 약한 역풍 수준입니다.","en":"Mentions are 20% below average, so retail interest is cool. Without a crowd yet, bull-market heat is a mild headwind."}},
  "구글 검색": {"ko":"검색창은 여전히 잠잠","en":"Search interest still low","why":{"ko":"비트코인 검색량은 새로 들어오는 개인 투자자의 규모를 보여줘요. 검색이 급증하면 신규 유입이 늘며 가격 상승에 힘이 실리기도 합니다.","en":"Bitcoin search volume reflects how many new retail investors are arriving. Surging searches can add fuel to price rallies."},"now":{"ko":"검색량이 평균보다 25% 낮아 신규 유입이 뜸한 상태예요. 대중의 관심이 붙기 전이라 지금은 약한 역풍으로 봅니다.","en":"Searches are 25% below average, so new inflows are sparse. Before public attention returns, this is a mild headwind."}},
  "앱 순위": {"ko":"앱스토어 순위 아직 멀어요","en":"App rank still far off","why":{"ko":"코인베이스 앱이 앱스토어 상위권이면 신규 가입자가 몰린다는 신호예요. 보통 시장이 뜨거울 때 순위가 급등하는 경향이 있습니다.","en":"A top App Store rank for Coinbase signals a rush of new sign-ups. Rankings tend to jump when the market is hot."},"now":{"ko":"순위가 35위로 상위권과 거리가 있어 신규 온보딩 열기는 약해요. 리테일 유입 측면에서는 역풍 쪽에 가깝습니다.","en":"Ranked 35th, far from the top, so new onboarding heat is weak. On retail inflows it leans toward a headwind."}},
  "ETF 플로우": {"ko":"ETF 자금 소폭 순유입 💰","en":"ETFs see small net inflows","why":{"ko":"현물 ETF로 돈이 들어오면 기관과 일반 투자자가 실제로 BTC를 사들인다는 뜻이에요. 유출이 이어지면 반대로 매수 압력이 줄어듭니다.","en":"Money flowing into spot ETFs means real BTC buying by institutions and investors. Sustained outflows reduce that buying pressure."},"now":{"ko":"7일 순유입 +$0.21B, 전일도 +$0.12B로 완만한 유입이 이어져요. 강한 수준은 아니지만 기관 수요는 약한 우호 쪽입니다.","en":"Seven-day net inflow is +$0.21B and yesterday added +$0.12B, a gentle inflow trend. Not strong, but institutional demand leans mildly supportive."}},
  "코인베이스 프리미엄": {"ko":"미국 수요는 중립 🧊","en":"US demand is neutral","why":{"ko":"코인베이스 가격이 글로벌보다 비싸면 미국 기관의 매수세가 강하다는 뜻이에요. 반대로 할인되면 미국 쪽 수요가 약하다는 신호입니다.","en":"If Coinbase trades above global prices, US institutional buying is strong. A discount signals weaker US demand."},"now":{"ko":"프리미엄이 0% 근처라 미국 수요가 강하지도 약하지도 않아요. 지금은 가격에 뚜렷한 영향을 주지 않는 중립 상태입니다.","en":"The premium is near 0%, so US demand is neither strong nor weak. Right now it has no clear effect on price."}},
  "CME 선물": {"ko":"기관 선물 열기 식었어요 🥶","en":"Institutional futures cooled","why":{"ko":"CME는 기관이 주로 쓰는 규제 선물 시장이에요. 미결제약정이 늘면 기관 관심과 레버리지가 커지고, 줄면 열기가 식었다는 뜻입니다.","en":"CME is the regulated futures venue used mainly by institutions. Rising open interest means more institutional interest and leverage; falling means cooling."},"now":{"ko":"월간 -8%로 기관의 선물 포지션이 줄어든 상태예요. 기관 참여 측면에서는 꽤 뚜렷한 역풍으로 작용하고 있습니다.","en":"Down 8% month over month, institutional futures positions have shrunk. On institutional participation it is a fairly clear headwind."}},
  "스테이블 공급": {"ko":"대기 자금 증가세는 더딤","en":"Dry powder grows slowly","why":{"ko":"스테이블코인은 코인 시장에 들어올 대기 매수 자금이에요. 공급이 빠르게 늘면 살 힘이 쌓이는 것이고, 정체되면 새 자금이 약하다는 뜻입니다.","en":"Stablecoins are waiting buy-side cash for crypto. Fast supply growth means building buying power; stagnation means weak fresh capital."},"now":{"ko":"공급은 약 $312B로 4주 +1.0% 증가에 그쳐 자금 유입이 완만해요. 마른 장작이 빠르게 쌓이는 단계는 아니라 약한 역풍입니다.","en":"Supply is about $312B, up just 1.0% in four weeks, so inflows are modest. Dry powder is not piling up fast, a mild headwind."}},
  "$STRC": {"ko":"스트래티지 자금줄 탄탄 💪","en":"Strategy funding looks solid","why":{"ko":"STRC는 액면 $100 근처를 유지하도록 설계된 Strategy의 우선주예요. 액면 위면 자금 조달이 수월해 BTC 추가 매수 여력이 커집니다.","en":"STRC is Strategy's preferred stock designed to trade near $100 par. Above par, fundraising is easy and capacity to buy more BTC grows."},"now":{"ko":"$99.41로 액면 바로 아래라 수요가 탄탄한 편이에요. 이틀 누적 -$0.09로 소폭 밀렸지만 의미 있는 약화는 아닙니다.","en":"At $99.41, just under par, demand looks firm. It slipped $0.09 over two days, but that is not meaningful weakening."}},
  "$MSTR": {"ko":"MSTR 주가는 아직 저점권","en":"MSTR still near lows","why":{"ko":"MSTR은 BTC를 대량 보유한 기업 주식이라 기관의 BTC 레버리지 수요를 비춰줘요. 52주 고점 근처면 수요가 강하고 저점 근처면 약합니다.","en":"MSTR is a company holding lots of BTC, so it mirrors institutional leveraged BTC demand. Near 52-week highs means strong demand; near lows means weak."},"now":{"ko":"$160로 52주 범위의 28% 위치라 하단 쪽에 머물러 있어요. 기관 레버리지 수요가 약해 중간 정도의 역풍으로 읽힙니다.","en":"At $160 it sits at 28% of its 52-week range, in the lower half. Institutional leverage demand is weak, a moderate headwind."}},
  "펀딩비": {"ko":"롱 쏠림은 과하지 않아요","en":"Longs not overcrowded","why":{"ko":"펀딩비는 무기한 선물에서 롱과 숏이 서로 주고받는 비용이에요. 크게 플러스면 롱이 과열돼 되돌림 위험이 커질 수 있습니다.","en":"Funding is the fee longs and shorts pay each other in perpetual futures. Strongly positive funding means crowded longs and higher pullback risk."},"now":{"ko":"실시간 변동 지표라 수시로 바뀌어요. 대체로 소폭 플러스면 롱이 약간 우세해도 과열은 아닌 우호적 환경으로 봅니다.","en":"This is a live metric that changes often. Mildly positive funding generally means a slight long bias without overheating, a supportive setup."}},
  "OI": {"ko":"레버리지 열기 체크 포인트","en":"Leverage heat to watch","why":{"ko":"미결제약정은 시장에 열려 있는 선물 포지션의 총량이에요. 빠르게 늘면 레버리지 과열로 급격한 청산 변동이 생기기 쉽습니다.","en":"Open interest is the total of outstanding futures positions. Rapid growth means leverage buildup, making sharp liquidation moves more likely."},"now":{"ko":"실시간 변동 지표라 수시로 바뀌어요. 완만한 증가는 시장 참여가 늘어난다는 뜻이지만 과열로 가면 변동성 위험이 커집니다.","en":"This is a live metric that changes often. Gradual growth means rising participation, but overheating raises volatility risk."}},
  "롱/숏": {"ko":"롱 우세, 쏠림은 지켜봐요","en":"Long-leaning, watch crowding","why":{"ko":"상위 트레이더들이 롱과 숏 중 어디에 더 베팅하는지 보여줘요. 한쪽으로 심하게 쏠리면 반대 방향 청산으로 급변동이 나올 수 있습니다.","en":"It shows whether top traders lean long or short. Extreme one-sided positioning can trigger sharp moves via liquidations of the other side."},"now":{"ko":"실시간 변동 지표라 수시로 바뀌어요. 롱이 다소 우세한 정도라면 심리는 우호적이지만 과도한 쏠림은 경계 대상입니다.","en":"This is a live metric that changes often. A modest long lean is supportive for sentiment, but extreme crowding deserves caution."}},
  "풋/콜": {"ko":"옵션 시장은 강세 베팅 🐂","en":"Options lean bullish","why":{"ko":"풋은 하락, 콜은 상승에 거는 옵션이에요. 풋 대비 콜이 많을수록 시장 참여자들이 오를 쪽에 더 많이 베팅하고 있다는 뜻입니다.","en":"Puts bet on declines and calls on rises. The more calls versus puts, the more participants are betting on upside."},"now":{"ko":"풋/콜 0.56으로 중립(~0.7)보다 낮아 콜이 우세해요. 옵션 시장 심리는 비교적 뚜렷한 우호 신호입니다.","en":"A put/call of 0.56 is below the ~0.7 neutral mark, so calls dominate. Options sentiment is a fairly clear supportive signal."}},
  "DVOL": {"ko":"변동성 잔잔, 폭풍 전 고요?","en":"Vol is calm for now","why":{"ko":"DVOL은 옵션 시장이 예상하는 비트코인 변동성이에요. 급등하면 불안이나 과열이 커졌다는 뜻이고, 낮으면 시장이 안정적이라는 신호입니다.","en":"DVOL is the volatility the options market expects for Bitcoin. A spike means rising fear or heat; low readings mean stability."},"now":{"ko":"DVOL 35.1로 낮은 편이라 시장이 조용해요. 큰 변동 기대가 약해 추세 탄력은 부족하고 약한 역풍으로 볼 수 있습니다.","en":"DVOL at 35.1 is low, so the market is quiet. Weak expectation of big moves means little trend momentum, a mild headwind."}},
  "SOPR": {"ko":"손실 매도 살짝 우세","en":"Slight loss-selling tilt","why":{"ko":"SOPR는 코인이 옮겨질 때 이익인지 손실인지를 보여주는 비율이에요. 1 위면 이익 실현, 1 아래면 손실 매도가 많다는 뜻입니다.","en":"SOPR shows whether coins moved on-chain were sold at profit or loss. Above 1 means profit-taking; below 1 means loss-selling."},"now":{"ko":"0.99로 1 바로 아래라 본전 부근에서 약간 손해 보고 파는 중이에요. 뚜렷한 방향성은 없고 아주 약한 역풍 수준입니다.","en":"At 0.99, just under 1, holders are selling slightly at a loss near breakeven. No clear direction, only a very mild headwind."}},
  "거래소 보유량": {"ko":"거래소서 코인 빠지는 중 🔒","en":"Coins leaving exchanges","why":{"ko":"거래소에 쌓인 코인은 바로 팔릴 수 있는 물량이에요. 인출이 늘면 장기 보유로 옮겨가 매도 가능 공급이 줄어 가격에 우호적입니다.","en":"Coins on exchanges can be sold quickly. Rising withdrawals mean moves to long-term holding, shrinking sellable supply, which is price-supportive."},"now":{"ko":"90일간 -6%로 거래소 물량이 꾸준히 줄고 있어요. 매도 가능 공급이 축소되는 중이라 꽤 분명한 우호 신호입니다.","en":"Down 6% over 90 days, exchange balances keep shrinking. Sellable supply is contracting, a fairly clear supportive signal."}},
  "채굴자 매도": {"ko":"채굴자 매도 압력 경계 ⚠️","en":"Miner selling pressure warning","why":{"ko":"Puell 배수는 채굴자 수익이 평소 대비 얼마나 큰지 보여줘요. 높으면 채굴자가 이익 실현으로 코인을 팔 유인이 커집니다.","en":"The Puell multiple shows miner revenue relative to normal. When high, miners have more incentive to sell coins for profit."},"now":{"ko":"Puell 1.06으로 채굴자 수익이 평균을 약간 웃돌아요. 매도 압력이 다소 있어 점수상으로는 비교적 큰 역풍으로 잡힙니다.","en":"Puell at 1.06 means miner revenue is slightly above average. Some selling pressure exists, scored as a fairly notable headwind."}},
  "고래 축적": {"ko":"고래들이 쓸어 담는 중 🐋","en":"Whales are accumulating","why":{"ko":"대형 지갑은 시장 흐름을 먼저 움직이는 큰손이에요. 이들이 꾸준히 사 모으면 공급이 줄고 장기 상승 기대가 커지는 신호로 읽힙니다.","en":"Large wallets are big players that move markets first. Steady accumulation shrinks supply and signals long-term upside expectations."},"now":{"ko":"고래 축적 점수가 +84로 매우 높아 큰손 매집이 뚜렷해요. 현재 가장 강한 우호 요인 중 하나로 가격 하단을 받쳐줍니다.","en":"The whale score of +84 is very high, showing clear big-holder accumulation. It is one of the strongest supports and helps underpin price."}},
  "USDT.D": {"ko":"위험선호 서서히 살아나요","en":"Risk appetite creeping back","why":{"ko":"USDT 도미넌스는 전체 시장에서 스테이블이 차지하는 비중이에요. 낮아지면 사람들이 스테이블을 코인으로 바꾸는 위험선호 신호입니다.","en":"USDT dominance is the stablecoin share of the total market. A decline means people are swapping stables into coins, a risk-on signal."},"now":{"ko":"6.34%로 스테이블 비중이 높지 않은 편이라 약한 우호 구간이에요. 대기 자금이 코인 쪽으로 움직일 여지가 있습니다.","en":"At 6.34%, the stablecoin share is not high, a mildly supportive zone. There is room for waiting cash to move into coins."}},
  "ATH 낙폭": {"ko":"고점 대비 -33%, 애매한 구간","en":"33% below ATH, in between","why":{"ko":"사상 최고가에서 얼마나 내려와 있는지는 사이클 위치를 보여줘요. 낙폭이 깊으면 바닥 기대와 약세 우려가 함께 존재합니다.","en":"Distance from the all-time high shows cycle position. A deep drawdown carries both bottoming hopes and bearish concerns."},"now":{"ko":"고점 대비 -32.7%로 점수가 -5라 사실상 중립이에요. 뚜렷한 우호도 역풍도 아니고 사이클 중간쯤에 있다는 정도입니다.","en":"At -32.7% from the high, the score is -5, essentially neutral. Neither a clear tailwind nor headwind, just mid-cycle positioning."}},
  "증시 쏠림": {"ko":"자금이 대형주에 갇혔어요 🧲","en":"Money stuck in megacaps","why":{"ko":"AI·반도체 같은 대형주에만 돈이 몰리면 위험자본이 코인까지 오기 어려워요. 상승이 넓게 퍼질 때 코인에도 자금이 흘러들기 쉽습니다.","en":"When money piles into megacaps like AI and chips, risk capital struggles to reach crypto. Broad rallies make it easier for funds to flow into coins."},"now":{"ko":"쏠림 지수가 99/100으로 52주 최상단이라 점수 -98의 강한 역풍이에요. 위험자본이 코인 밖에 묶여 있는 상태입니다.","en":"The concentration index is 99/100, at the 52-week extreme, a strong headwind scored -98. Risk capital is tied up outside crypto."}},
  "FED 유동성": {"ko":"시중 유동성 살짝 마르는 중","en":"Liquidity draining slightly","why":{"ko":"연준 대차대조표에서 TGA와 RRP를 뺀 값이 시중에 실제 풀린 돈이에요. 이 돈이 늘면 위험자산으로 흘러 BTC에 우호적입니다.","en":"The Fed balance sheet minus TGA and RRP is the money actually in markets. When it grows, it flows into risk assets, favoring BTC."},"now":{"ko":"약 $5.43조로 3개월간 -1.3% 줄었어요. 유동성이 소폭 빠지는 중이라 약한 역풍이지만 급격한 수축은 아닙니다.","en":"About $5.43T, down 1.3% over three months. Liquidity is slightly receding, a mild headwind but not a sharp contraction."}},
  "M2 유동성": {"ko":"통화량은 완만히 늘어요","en":"Money supply grows steadily","why":{"ko":"M2는 시중 통화량이에요. 돈이 많이 풀리면 자산 가격이 오르기 쉽고, 비트코인은 M2와 시차를 두고 같이 움직이는 경향이 있습니다.","en":"M2 is the money supply. More money tends to lift asset prices, and Bitcoin has tended to move with M2 with a lag."},"now":{"ko":"미국 M2가 전년 대비 +5.66% 늘어 약한 우호 요인이에요. 후행 지표라 단기 가격보다는 중기 배경 정도로 보면 됩니다.","en":"US M2 is up 5.66% year over year, a mild tailwind. As a lagging indicator, it is more a medium-term backdrop than a short-term driver."}},
  "미국 증시 추세": {"ko":"미 증시 횡보, 방향 탐색","en":"US stocks drifting sideways","why":{"ko":"코인은 주식과 위험선호 흐름을 공유하는 경우가 많아요. 증시가 오르면 투자 심리가 좋아져 코인에도 우호적으로 작용하기 쉽습니다.","en":"Crypto often shares risk appetite with stocks. Rising equities lift sentiment and tend to help crypto as well."},"now":{"ko":"SPY가 1주 -0.2%로 사실상 횡보라 영향은 거의 중립이에요. 위험선호가 뚜렷하게 늘지도 줄지도 않는 상태입니다.","en":"SPY is down 0.2% over a week, basically flat, so impact is near neutral. Risk appetite is neither clearly rising nor falling."}},
  "CLARITY": {"ko":"규제 명확화 사실상 무산 🚧","en":"Regulatory clarity all but dead","why":{"ko":"CLARITY 법안은 미국의 코인 시장 규칙을 정하는 법이에요. 통과 가능성이 높을수록 규제 불확실성이 줄어 기관 참여에 우호적입니다.","en":"The CLARITY Act sets US crypto market rules. Higher passage odds reduce regulatory uncertainty, favoring institutional participation."},"now":{"ko":"통과확률이 5%로 상원 9/15 부결 후 연내 서명은 어려워 보여요. 규제 명확성 기대가 거의 꺼진 강한 역풍입니다.","en":"Odds are 5% after the Senate vote failed on 9/15, so signing this year looks unlikely. Hopes for clarity have faded, a strong headwind."}},
  "DXY": {"ko":"달러 힘 빠지며 살짝 우호","en":"Softer dollar, slight tailwind","why":{"ko":"달러가 강해지면 위험자산에서 돈이 빠져나가는 경향이 있어요. 달러가 약해지면 상대적으로 코인 같은 자산에 우호적입니다.","en":"A stronger dollar tends to pull money out of risk assets. A weaker dollar is relatively favorable for assets like crypto."},"now":{"ko":"달러지수 120.3으로 3개월 -0.5%의 소폭 약세예요. 영향은 크지 않지만 코인에는 약한 우호 요인입니다.","en":"The dollar index is 120.3, down a slight 0.5% over three months. The effect is small but a mild positive for crypto."}},
  "반도체 독주장": {"ko":"반도체가 돈 다 빨아들여요 🔌","en":"Chips are hogging the cash","why":{"ko":"반도체가 시장보다 훨씬 강하면 위험자금이 그쪽으로 쏠려요. 그만큼 코인으로 흘러올 자금이 줄어 역방향 신호로 활용됩니다.","en":"When chips far outperform the market, risk money piles in there, leaving less to flow into crypto. It is used as an inverse signal."},"now":{"ko":"SMH가 S&P 대비 1개월 +13.9%로 독주해 점수 -100의 최대 역풍이에요. 이틀 누적 +0.9%p로 쏠림이 더 이어지고 있습니다.","en":"SMH leads the S&P by 13.9% over a month, a maximum headwind scored -100. It added 0.9pp over two days, so the concentration keeps extending."}}
};
const COMMENT_DAILY_AT = "2026-10-04 00:01 KST";
