'use strict';
/* ============================================================
   지표별 한 줄 코멘트 (노란 글씨, 툴팁 맨 아래) — app.js 가 현재 점수로 골라 표시.
   버킷: [0]=코인 우호(표시>=20) · [1]=중립 · [2]=코인 약세(표시<=-20).
   실시간 값에 따라 자동 전환(별도 갱신 작업 불필요). 7월 FOMC 등 pending 은 고정 문구.
   ============================================================ */
const COMMENT = {
  '김프':            { ko:['김프 붙는중 🔥 국내 FOMO','김프 잠잠','역프 — 국내 외면'],
                       en:['Kimchi premium heating 🔥','Kimchi premium flat','Reverse premium — Korea cold'] },
  '공포·탐욕':        { ko:['탐욕 모드 🤑 과열 주의','심리 중립','극단적 공포 — 바닥 신호?'],
                       en:['Greed mode 🤑 watch overheating','Sentiment neutral','Extreme fear — a bottom?'] },
  '소셜 멘션':        { ko:['소셜 들썩 — 리테일 관심↑','소셜 잠잠','아무도 안 떠듦'],
                       en:['Social buzzing','Social quiet','Crickets'] },
  '구글 검색':        { ko:['검색 급증 — 신규 유입 신호','검색 평이','아무도 안 찾음'],
                       en:['Searches spiking — new inflow','Searches flat','Nobody searching'] },
  '앱 순위':          { ko:['앱순위 급등 — 리테일 온보딩','앱순위 평범','앱순위 바닥 — 리테일 무관심'],
                       en:['App rank climbing — onboarding','App rank mid','App rank bottom — no retail'] },
  'ETF 플로우':       { ko:['ETF 자금 유입 — 기관이 산다','ETF 플로우 미지근','ETF 자금 유출 — 기관 이탈'],
                       en:['ETF inflows — institutions buying','ETF flows tepid','ETF outflows — exits'] },
  '코인베이스 프리미엄': { ko:['미국이 산다 (CB 프리미엄)','CB 프리미엄 중립','미국이 던진다 (역프리미엄)'],
                       en:['US bidding (CB premium)','CB premium flat','US selling (discount)'] },
  'CME 선물':         { ko:['기관 레버리지 붙는중','CME 잠잠','기관 발 빼는중'],
                       en:['Institutions leveraging up','CME quiet','Institutions backing off'] },
  '스테이블 공급':     { ko:['마른장작 쌓이는중 — 대기 매수금↑','스테이블 횡보','스테이블 줄어듦 — 화력 약화'],
                       en:['Dry powder building','Stables flat','Stables shrinking — less fuel'] },
  '$STRC':           { ko:['STRC 액면 위 — 수요 강함','STRC par 부근','STRC 액면 붕괴 — 수요 약함'],
                       en:['STRC above par — strong demand','STRC near par','STRC below par — weak'] },
  '$MSTR':           { ko:['MSTR 고점권 — 레버리지 수요 강함','MSTR 중간','MSTR 바닥권 — 수요 죽음'],
                       en:['MSTR near highs — strong demand','MSTR mid-range','MSTR near lows — demand dead'] },
  '펀딩비':           { ko:['펀딩 양수 — 롱 우위','펀딩 균형','펀딩 음수 — 숏 우위'],
                       en:['Funding positive — longs lead','Funding balanced','Funding negative — shorts lead'] },
  'OI':              { ko:['미결제 증가 — 관심↑','OI 평이','미결제 급감 — 디레버리징'],
                       en:['OI rising — interest up','OI flat','OI dropping — deleveraging'] },
  '롱/숏':            { ko:['롱 쏠림 — 낙관(과열?)','롱숏 균형','숏 쏠림 — 비관 극단'],
                       en:['Longs crowded — optimism','L/S balanced','Shorts crowded — extreme pessimism'] },
  '풋/콜':            { ko:['콜 우위 — 강세 베팅','옵션 중립','풋 우위 — 헤지/약세'],
                       en:['Calls favored — bullish bets','Options neutral','Puts favored — hedging'] },
  'DVOL':            { ko:['변동성 높음 — 크게 출렁','변동성 보통','변동성 낮음 — 잠잠'],
                       en:['Vol high — big swings','Vol normal','Vol low — quiet'] },
  'SOPR':            { ko:['이익실현 우위','SOPR 손익분기','손절 우위 — 항복?'],
                       en:['Profit-taking dominant','SOPR breakeven','Loss-taking — capitulation?'] },
  '거래소 보유량':     { ko:['거래소서 코인 빠짐 — 공급↓(강세)','거래소 잔고 횡보','거래소로 유입 — 매도 대기'],
                       en:['Coins leaving exchanges — bullish','Exchange balance flat','Coins flowing in — sell-ready'] },
  '채굴자 매도':       { ko:['채굴자 조용 — 매도압력 낮음','채굴자 보통','채굴자 던지는중 — 분배 압력'],
                       en:['Miners quiet — low sell pressure','Miners normal','Miners selling — distribution'] },
  '고래 축적':         { ko:['고래 매집중 🐳','고래 관망','고래 분산중 — 물량 푸는중'],
                       en:['Whales accumulating 🐳','Whales idle','Whales distributing'] },
  'USDT.D':          { ko:['테더 비중↓ — 위험선호 ON','USDT.D 중립','테더로 도피 — 위험회피'],
                       en:['USDT.D falling — risk-on','USDT.D neutral','Fleeing to Tether — risk-off'] },
  'ATH 낙폭':         { ko:['고점 근접 — 사이클 후반','사이클 중간','고점서 한참 — 깊은 조정'],
                       en:['Near ATH — late cycle','Mid-cycle','Far from ATH — deep drawdown'] },
  '증시 쏠림':         { ko:['시장 골고루 — 확산(우호)','쏠림 보통','소수 대형주 쏠림 — 코인 밖에 돈 묶임'],
                       en:['Market broad — healthy','Concentration mid','Megacaps hog it — crypto starved'] },
  'FED 유동성':       { ko:['유동성 콸콸 🚰 위험자산 우호','유동성 잠잠','유동성 말라간다 ⚠️'],
                       en:['Liquidity gushing 🚰 risk-on','Liquidity flat','Liquidity drying up ⚠️'] },
  'M2 유동성':        { ko:['돈 풀리는중 — 후행 호재','M2 보통','통화 긴축 — 역풍'],
                       en:['Money printer on','M2 normal','Tightening — headwind'] },
  '미국 증시 추세':    { ko:['증시 상승추세 — 위험선호','증시 횡보','증시 하락추세 — 리스크오프'],
                       en:['Stocks uptrend — risk-on','Stocks flat','Stocks downtrend — risk-off'] },
  'CLARITY':         { ko:['통과 기대↑ — 규제 호재','통과 반반','통과 난망 — 규제 불확실'],
                       en:['Passage likely — bullish','Coin-flip odds','Passage unlikely — uncertain'] },
  '7월 FOMC':         { ko:['금리 결정 대기 — 7/30 새벽3시','금리 결정 대기 — 7/30 새벽3시','금리 결정 대기 — 7/30 새벽3시'],
                       en:['Rate decision pending — Jul 30','Rate decision pending — Jul 30','Rate decision pending — Jul 30'] },
  'DXY':             { ko:['달러 약세 — 코인 우호','달러 중립','달러 강세 — 역풍'],
                       en:['Dollar weak — tailwind','Dollar neutral','Dollar strong — headwind'] },
  '반도체 독주장':     { ko:['반도체 식는중 — 코인 차례?','반도체 그저그럼','반도체 독주중 — 코인엔 관심 0'],
                       en:['Semis cooling — crypto turn?','Semis meh','Semis dominating — crypto ignored'] },
};
