'use strict';
/* AI 일일 코멘트 — daily-commentary.yml 자동 생성(wrap_commentary.mjs). app.js 가 우선 사용, 없으면 commentary.js/desc 로 fallback. */
const COMMENT_DAILY = {
  "김프": {"ko":"김프 마이너스, 냉기 이틀째","en":"Kimchi premium turns colder","why":{"ko":"국내 시세가 해외보다 비싼 정도라 한국 리테일 열기를 보여주는 지표다. 김프가 높으면 국내 투자 수요가 강하다는 뜻.","en":"It measures how much pricier BTC is in Korea vs abroad, tracking Korean retail buying heat."},"now":{"ko":"프리미엄이 마이너스로 떨어졌고 이틀 연속 하락 중이라 국내 매수 열기가 식고 있다는 신호.","en":"The premium has turned negative and kept falling for two days, showing Korean retail demand cooling."}},
  "공포·탐욕": {"ko":"공포 구간 근접","en":"Nearing extreme fear","why":{"ko":"투자자 심리를 0~100으로 수치화한 지표로, 극단적 공포·탐욕은 종종 단기 변곡점 근처에서 나타난다.","en":"This gauges investor sentiment 0-100; extremes often mark short-term turning points."},"now":{"ko":"지수가 30으로 공포 구간에 있어 리테일 심리가 위축된 상태, 극공포(25) 근접이 부담.","en":"At 30 it sits in fear territory, close to extreme fear, showing retail sentiment is shaky."}},
  "소셜 멘션": {"ko":"SNS 관심 시들","en":"Social buzz fading","why":{"ko":"X·레딧 등에서 코인 언급이 늘면 리테일 관심과 FOMO가 커진다는 뜻이라 대중 심리 가늠자로 쓰인다.","en":"Rising social mentions signal growing retail interest and FOMO around crypto."},"now":{"ko":"평균 대비 20% 낮아 리테일 관심이 평소보다 식어 있는 상태, 대중 유입 동력은 약함.","en":"Mentions are 20% below average, indicating retail attention is currently subdued."}},
  "구글 검색": {"ko":"검색량도 한풀 꺾임","en":"Search interest cooling","why":{"ko":"'비트코인' 등 검색량은 신규 개인 투자자 유입의 선행 지표로, 급증하면 대중 관심이 폭발했다는 뜻.","en":"Search volume for bitcoin is a leading signal of new retail investors entering the market."},"now":{"ko":"평균보다 25% 낮은 검색량으로 신규 유입 신호가 약함, 대중적 관심은 아직 낮은 편.","en":"Search volume is 25% below average, suggesting little fresh retail interest right now."}},
  "앱 순위": {"ko":"코인베이스 앱, 순위 밖","en":"Coinbase app off the charts","why":{"ko":"앱스토어 순위가 오르면 신규 유저 다운로드가 급증했다는 뜻이라 리테일 온보딩 속도를 보여준다.","en":"A rising app store rank means surging downloads, tracking how fast new retail users are onboarding."},"now":{"ko":"35위권에 머물러 있어 신규 리테일 유입이 활발하지 않은 상태로 볼 수 있다.","en":"Sitting around rank 35, this suggests new retail onboarding isn't particularly active."}},
  "ETF 플로우": {"ko":"ETF 순유입 이어짐","en":"ETF inflows continue","why":{"ko":"미국 현물 ETF 자금 흐름은 기관 매수 규모를 직접 보여줘 가격에 큰 영향을 주는 핵심 지표다.","en":"US spot ETF flows show direct institutional buying pressure, a key driver of price."},"now":{"ko":"7일 누적 +4.8억달러 순유입으로 기관 수요가 이어지고 있어 완만한 우호적 흐름.","en":"A 7-day net inflow of about $480M shows steady institutional demand, a mild tailwind."}},
  "코인베이스 프리미엄": {"ko":"美 수요 살짝 약함","en":"US demand slightly soft","why":{"ko":"코인베이스(달러) 가격이 글로벌보다 비싸면 미국 기관 매수세가 강하다는 뜻으로 해석된다.","en":"A premium on Coinbase (USD) vs global prices signals stronger US institutional buying."},"now":{"ko":"프리미엄이 소폭 마이너스라 미국발 매수세가 글로벌 대비 약간 처져 있는 정도, 영향은 크지 않음.","en":"The slight negative premium shows US buying lagging global markets a touch, a minor drag."}},
  "CME 선물": {"ko":"CME 관심 뚝","en":"CME interest drops","why":{"ko":"시카고상품거래소 선물은 기관 자금의 진입 척도로, 미결제약정이 늘면 기관 관심·레버리지가 커졌다는 뜻.","en":"CME futures OI tracks institutional participation; rising OI means more institutional leverage."},"now":{"ko":"한달새 미결제약정이 8% 줄어 기관 자금의 관심이 식고 있다는 신호로 다소 역풍.","en":"Open interest fell 8% in a month, signaling cooling institutional interest, a modest headwind."}},
  "스테이블 공급": {"ko":"마른 장작 줄어드는 중","en":"Dry powder shrinking","why":{"ko":"USDT+USDC 시총은 코인 매수 대기자금이라 늘면 향후 매수여력(마른 장작)이 커진다는 뜻.","en":"Stablecoin supply is buy-side dry powder; a growing total means more potential future buying."},"now":{"ko":"4주간 공급이 1.1% 줄어 대기자금이 오히려 축소되는 흐름이라 매수여력 측면에서 역풍.","en":"Supply shrank 1.1% over four weeks, meaning sidelined capital is shrinking, a headwind for buying power."}},
  "$STRC": {"ko":"액면가 향해 이틀째 회복","en":"Recovering toward par, 2 days","why":{"ko":"MSTR의 스트레치 우선주는 액면 $100 유지가 설계 목표라 그 근접도가 기관의 BTC 신뢰도를 보여준다.","en":"Strategy's STRC preferred stock is designed to hold near $100 par, so its level reflects institutional confidence in the BTC trade."},"now":{"ko":"$95.01로 액면 아래지만 이틀 연속 소폭 상승 중이라 수요가 서서히 회복되는 모습.","en":"At $95.01, below par but up two days straight, showing demand gradually recovering."}},
  "$MSTR": {"ko":"52주 바닥권, 이틀째 반등","en":"Near 52wk low, up 2 days","why":{"ko":"MSTR은 BTC를 대량 보유한 트레저리 주식이라 52주 범위 내 위치가 기관 레버리지 수요의 온도를 보여준다.","en":"MSTR holds massive BTC reserves, so its position in the 52-week range reflects institutional leverage demand."},"now":{"ko":"52주 범위 하위 6%로 저점권이지만 이틀 연속 반등 중이라 바닥에서 힘이 살아나는 조짐.","en":"It's near the bottom 6% of its 52-week range, but climbing for two days, an early sign of life at the lows."}},
  "펀딩비": {"ko":"펀딩비, 완만한 롱 우세","en":"Funding mildly long-tilted","why":{"ko":"무기한 선물 펀딩비는 롱·숏 쏠림을 보여줘, 과도하게 높으면 롱 과열로 되돌림 위험이 커진다.","en":"Perpetual funding rates show long vs short crowding; very high rates flag overheated longs prone to reversals."},"now":{"ko":"실시간 값이라 자주 바뀌는 지표로, 서버 조회 제약상 최신 수치는 아닐 수 있어 방향성만 참고할 것.","en":"This updates constantly and the current read may be delayed, so treat it as directional context only."}},
  "OI": {"ko":"미결제약정 완만 증가 흐름","en":"Open interest trending up","why":{"ko":"선물 미결제약정이 늘면 레버리지 자금이 커진다는 뜻으로 시장 과열·활력 정도를 보여준다.","en":"Rising futures open interest means more leveraged money in the market, a gauge of activity or overheating."},"now":{"ko":"실시간성 지표라 수시로 바뀌며 서버 제약상 최신값이 아닐 수 있어 수준보다 추세로만 참고.","en":"This shifts constantly and may not reflect the latest reading, so read it as a trend, not a precise level."}},
  "롱/숏": {"ko":"롱 쏠림 다소 존재","en":"Some long-side crowding","why":{"ko":"상위 트레이더의 롱/숏 포지션 비율로, 한쪽으로 쏠리면 청산 연쇄(숏스퀴즈·롱스퀴즈) 위험이 커진다.","en":"This tracks top traders' long/short skew; heavy crowding on one side raises liquidation-cascade risk."},"now":{"ko":"실시간 지표라 값이 자주 바뀌고 최신이 아닐 수 있어, 현재는 롱쪽에 다소 쏠린 정도로만 참고.","en":"As a live metric that may lag, treat this only as a rough sign of mild long-side crowding right now."}},
  "풋/콜": {"ko":"옵션시장 콜 선호","en":"Options favor calls","why":{"ko":"옵션 풋/콜 미결제 비율은 옵션 트레이더들의 방향성 베팅을 보여줘, 낮을수록 상승 베팅이 많다는 뜻.","en":"The put/call open interest ratio shows options traders' directional bets; lower means more upside bets."},"now":{"ko":"0.58로 중립(0.7)보다 낮아 콜(상승) 베팅이 우위인 상태, 옵션시장은 다소 우호적.","en":"At 0.58, below the 0.7 neutral level, calls outweigh puts, a mildly bullish tilt in options positioning."}},
  "DVOL": {"ko":"변동성 다소 고조","en":"Volatility somewhat elevated","why":{"ko":"옵션 내재변동성(DVOL)은 시장이 앞으로의 급변을 얼마나 우려하는지 보여줘 과열·패닉을 가늠하는 지표다.","en":"Implied volatility (DVOL) shows how much turbulence the market expects, a gauge of fear or complacency."},"now":{"ko":"변동성이 다소 높은 편이라 시장이 불안정성을 경계하는 상태, 위험선호에는 부담 요인.","en":"Volatility sits on the elevated side, showing the market is bracing for turbulence, a modest headwind."}},
  "SOPR": {"ko":"실현손익, 소폭 손실 우위","en":"Realized P&L tilts to loss","why":{"ko":"SOPR은 코인을 판 사람들이 이익인지 손실인지를 보여줘 시장 참여자들의 매도 심리를 가늠하게 한다.","en":"SOPR shows whether sellers are realizing gains or losses, a gauge of market participants' selling psychology."},"now":{"ko":"0.99로 1 아래라 손실 매도가 이익 매도보다 소폭 많은 상태, 약한 항복 신호지만 크지 않음.","en":"At 0.99, just below 1, slightly more coins are sold at a loss than a gain, a mild but minor capitulation sign."}},
  "거래소 보유량": {"ko":"거래소 물량 계속 빠짐","en":"Coins leaving exchanges","why":{"ko":"거래소에서 코인이 빠져나가면 즉시 팔 수 있는 물량이 줄어드는 셈이라 장기보유·공급축소 신호로 읽힌다.","en":"Coins leaving exchanges means less supply ready to sell immediately, signaling long-term holding."},"now":{"ko":"90일간 보유량이 6% 줄어 거래소 공급이 계속 축소 중, 구조적으로 우호적인 흐름.","en":"Exchange balances fell 6% over 90 days, a steady supply squeeze that's structurally supportive."}},
  "채굴자 매도": {"ko":"채굴자발 매도 부담","en":"Miner selling pressure","why":{"ko":"채굴자 수익성 지표(Puell)는 채굴자들이 코인을 얼마나 팔아야 할 압박을 받는지 보여주는 공급측 변수다.","en":"The Puell-based miner metric gauges how much sell pressure miners face to cover costs, a supply-side factor."},"now":{"ko":"현재 수준은 채굴자발 매도 압박이 있는 구간으로 읽혀 공급측에서 약한 역풍으로 작용.","en":"The current reading points to a miner-driven selling pressure zone, a mild supply-side headwind."}},
  "고래 축적": {"ko":"고래들 계속 쓸어담는 중","en":"Whales keep accumulating","why":{"ko":"대형 지갑의 매집·분배 흐름은 스마트머니로 불리는 큰손들의 방향성 베팅을 보여주는 지표다.","en":"Large wallet accumulation vs distribution tracks the directional bets of so-called smart money."},"now":{"ko":"지표가 강한 매집 구간을 가리켜 고래들이 적극적으로 사모으는 중, 구조적으로 우호적.","en":"The gauge points to strong accumulation, with whales actively buying, a structurally bullish sign."}},
  "USDT.D": {"ko":"스테이블 비중 다소 높음","en":"Stablecoin share elevated","why":{"ko":"전체 코인 시총에서 스테이블코인 비중이 줄면 그 자금이 위험자산(비트코인 등)으로 이동했다는 뜻의 역지표다.","en":"A falling stablecoin dominance means capital is rotating into risk assets like BTC — this is an inverse indicator."},"now":{"ko":"테더 도미넌스가 상대적으로 높은 편이라 자금이 아직 스테이블에 머물러 위험선호가 약한 신호.","en":"Stablecoin dominance is on the higher side, meaning capital is still parked there rather than in risk assets."}},
  "ATH 낙폭": {"ko":"전고점 대비 반토막 근처","en":"Near half off the peak","why":{"ko":"사상 최고가로부터의 낙폭은 지금이 사이클의 어느 단계(초입·중반·바닥)인지 가늠하게 해주는 지표다.","en":"Distance from the all-time high helps gauge where BTC sits in its market cycle."},"now":{"ko":"고점 대비 48.5% 하락한 상태로 상당한 조정 국면, 사이클상 초반은 아닌 것으로 해석된다.","en":"BTC sits 48.5% below its all-time high, a sizable drawdown suggesting it's past the early cycle stage."}},
  "증시 쏠림": {"ko":"쏠림도 거의 중립","en":"Market breadth near neutral","why":{"ko":"대형주(주로 AI·반도체)로 자금이 쏠리면 위험자본이 그쪽에 묶여 코인으로 흘러올 여력이 줄어든다.","en":"When capital concentrates in mega-caps (mainly AI/chips), less risk capital is free to flow into crypto."},"now":{"ko":"52주 범위 중간 수준으로 쏠림이 심하지도 분산되지도 않은 중립 상태, 영향은 미미.","en":"Sitting at the midpoint of its 52-week range, concentration is neither extreme nor spread out — a negligible effect."}},
  "FED 유동성": {"ko":"연준 유동성 거의 제자리","en":"Fed liquidity nearly flat","why":{"ko":"Fed 대차대조표에서 재무부·역레포 계좌를 뺀 순유동성은 위험자산에 흘러갈 실질 자금량을 보여주는 핵심 변수다.","en":"Fed net liquidity (balance sheet minus TGA and RRP) tracks the real pool of cash available for risk assets."},"now":{"ko":"3개월간 거의 보합이라 유동성 환경은 중립에 가까움, 최근 이틀도 소폭 증가에 그침.","en":"Nearly flat over three months, the liquidity backdrop is close to neutral, with only a small uptick lately."}},
  "M2 유동성": {"ko":"통화량 완만히 증가 중","en":"Money supply growing steadily","why":{"ko":"글로벌 통화량(M2)이 늘면 시중에 돈이 많아져 시차를 두고 위험자산·코인 가격에 우호적으로 작용한다.","en":"Rising global M2 money supply means more cash in the system, which tends to lift risk assets with a lag."},"now":{"ko":"미국 M2가 전년비 5.53% 늘어난 상태로 완만한 유동성 확장 국면, 코인에 후행적으로 우호적.","en":"US M2 is up 5.53% year over year, a gentle liquidity expansion that tends to favor crypto with a lag."}},
  "미국 증시 추세": {"ko":"증시 강한 상승세","en":"Stocks rallying hard","why":{"ko":"S&P500 단기 추세는 위험선호 심리를 가장 빠르게 보여줘 코인과 같은 방향으로 움직이는 경우가 많다.","en":"S&P 500's short-term trend is a fast read on risk appetite, which often moves in lockstep with crypto."},"now":{"ko":"최근 1주 3.5% 상승한 강한 추세로 위험선호가 살아있어 코인에도 우호적인 배경.","en":"Up 3.5% over the past week, this strong uptrend shows healthy risk appetite, a tailwind for crypto too."}},
  "CLARITY": {"ko":"규제법안 통과 기대 낮음","en":"Crypto bill odds still low","why":{"ko":"미국 시장구조법(CLARITY Act) 통과는 코인에 대한 규제 불확실성을 없애줘 기관 자금 유입의 문턱을 낮춘다.","en":"Passage of the CLARITY Act would remove regulatory uncertainty, lowering the barrier to institutional inflows."},"now":{"ko":"예측시장 확률이 16%로 낮고 최근 이틀새 더 낮아져 규제 불확실성이 여전히 부담 요인.","en":"Prediction-market odds sit at just 16% and slipped further over two days, keeping regulatory uncertainty a drag."}},
  "DXY": {"ko":"달러 완만한 강세","en":"Dollar mildly firming","why":{"ko":"달러가 강해지면 다른 자산(코인 포함)이 상대적으로 비싸져 보여 자금이 덜 몰리는 역풍으로 작용한다.","en":"A stronger dollar makes other assets, including crypto, relatively more expensive, a headwind for inflows."},"now":{"ko":"3개월간 0.9% 오른 완만한 달러 강세로 코인에는 약한 역풍 정도로 작용하는 수준.","en":"The dollar is up a mild 0.9% over three months, a modest but real headwind for crypto right now."}},
  "반도체 독주장": {"ko":"반도체 쏠림 이틀째 완화","en":"Chip crowding easing, 2 days","why":{"ko":"반도체가 시장을 압도적으로 앞서면 위험자본이 그쪽에 쏠려 코인으로 흘러올 자금이 줄어드는 역지표다.","en":"When semiconductors dominate market gains, risk capital concentrates there, leaving less for crypto — an inverse signal."},"now":{"ko":"반도체가 최근 한달 시장 대비 부진해 쏠림이 이틀 연속 풀리는 중, 코인엔 우호적인 흐름.","en":"Chips have lagged the broader market over the past month and kept easing for two days, a tailwind for crypto."}}
};
const COMMENT_DAILY_AT = "2026-08-08 20:21 KST";
